### ISSUE TITLE
您好，我在将本插件导入其他插件时出现如下错误

### ISSUE THREAD

**Issue by qienoob** [mobyw/nonebot-plugin-txt2img#2]
02-05 13:28:37 [ERROR] nonebot | Running Matcher(type='message', module=nbnebot_plugin_wtbot) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\bot\text3\text3\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\bot\text3\text3\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\text3\text3\.venv\lib\site-packages\nbnebot_plugin_wtbot\__init__.py", line 87, in _
    pic = txt2img.draw(title, text)
  File "D:\bot\text3\text3\.venv\lib\site-packages\nonebot_plugin_txt2img\txt2img.py", line 81, in draw
    title_font = ImageFont.truetype(self.font_family, self.title_font_size)
  File "D:\bot\text3\text3\.venv\lib\site-packages\PIL\ImageFont.py", line 1008, in truetype
    return freetype(font)
  File "D:\bot\text3\text3\.venv\lib\site-packages\PIL\ImageFont.py", line 1005, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\bot\text3\text3\.venv\lib\site-packages\PIL\ImageFont.py", line 255, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by qienoob** [comment]
已确认其他功能无误

**Comment by qienoob** [comment]
已通过手动导入文字库与图片解决
