### ISSUE TITLE
已配置ForwardDriver仍直接退出

### ISSUE THREAD

**Issue by ABKQPO** [mobyw/nonebot-plugin-txt2img#7]
配置

```
DRIVER=fastapi+~httpx+~websockets+~aiohttp
```

```
10-14 09:47:54 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 36, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 30, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_txt2img\__init__.py", line 33, in start
    flag = await download_template()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_txt2img\download.py", line 56, in download_template
    raise RuntimeError(message)
RuntimeError: 当前驱动器 Driver(type='fastapi', adapters=2, bots=0) 不支持 ForwardDriver，请配置合适的驱动器
```

**Comment by mobyw** [comment]
```
DRIVER=~fastapi+~httpx
```

`~` 是 `nonebot.driver.` 的简写

**Comment by ABKQPO** [comment]
即使不加载fastapi也这样

**Comment by mobyw** [comment]
修改

```
LOG_LEVEL=DEBUG
```

查看启动时读取到的环境变量是否是修改的配置的

**Comment by ABKQPO** [comment]
{'driver': '~fastapi', 'host': IPv4Address('0.0.0.0'), 'port': 10500, 'log_level': 'DEBUG', 'api_timeout': 60.0, 'superusers': {'2407187481'}, 'nickname': {'HF'}, 'command_start': {'.', '/'}, 'command_sep': {' /'}
driver没有识别

**Comment by mobyw** [comment]
是否有使用多个环境变量配置文件，`.env.prod` 的优先级是高于 `.env` 的，如果系统环境变量有对应的值优先级会更高

**Comment by ABKQPO** [comment]
没有设置环境，使用.env.prod配置文件

**Comment by mobyw** [comment]
发一下修改后的完整 `.env.prod` 看看呢，敏感信息记得隐去

**Comment by ABKQPO** [comment]
```
DRIVER=~fastapi+~httpx+~websocket
LOG_LEVEL=DEBUG
HOST=0.0.0.0  # 配置 NoneBot2 监听的 IP/主机名
PORT=10500  # 配置 NoneBot2 监听的端口
SUPERUSERS=["2407187481"]  # 配置 NoneBot 超级用户
bot_name=HF  #机器人的名称
NICKNAME=["HF"]  # 配置机器人的昵称
COMMAND_START=["/","."]  # 配置命令起始字符
COMMAND_SEP=[" /"]  # 配置命令分割字符
API_TIMEOUT=600 # 超时，单位 s，建议根据你上传带宽灵活配置

#以下是插件的配置


#webui
web_host = "127.0.0.1"
web_port = 8666

#消息伪造
fake_split="|"

#Rsshub订阅
rss_proxy="127.0.0.1:7890"
rsshub_backup=["http://127.0.0.1:1200"]
qb_web_url="127.0.0.1:8081"
qb _down_path="D:\NoneBot\ABK\data\elf_rss"

#动漫识别
animetrace_model_anime="lovelive"
animetrace_model_gal="kirakira"

#面包店
special_thing_group={"1145888872": ["派蒙", "面包", "应急食品"]}
level_bread_num=20

#sudo
SUDOERS=["2407187481"]

#状态
PS_CUSTOM_BG=["file:///D:/NoneBot/ABK/data/picstatus/-5f64eb9aa6a2de85.png"]
PS_IGNORE_NETS=["^Clash"]
# 需要进行测试响应速度的网址列表（可空）
PS_TEST_SITES='
[
    {"name": "Baidu", "url": "https://www.baidu.com/"},
    {"name": "Google", "url": "https://www.google.com/", "use_proxy": true},
    {"name": "Bing", "url": "https://www.bing.com/", "use_proxy": true},
    {"name": "Pixiv", "url": "https://pixiv.net/", "use_proxy": true},
    {"name": "ChatGPT", "url": "https://chat.openai.com", "use_proxy": true},
    {"name": "Claude", "url": "https://claude.ai/", "use_proxy": true}
]
'
# 要忽略的进程名（可空）
# 使用正则表达式匹配（注意事项同上）
PS_IGNORE_PROCS=["^Clash"]

# 进程列表的排序方式（可空）
# 可选：cpu、mem
PS_PROC_SORT_BY=mem

# 是否将进程 CPU 占用率显示为类似 Windows 任务管理器的百分比（最高 100%）（可空）
# 例：当你的 CPU 总共有 4 线程时，如果该进程吃满了两个线程，
# Linux 会显示为 200%（每个线程算 100%），而 Windows 会显示为 50%（总占用率算 100%）
PS_PROC_CPU_MAX_100P=True

#远程同意好友
master_id = ["2407187481","2417682117"]
group_request = True      # 开启群聊申请处理

#mc更新
mcver_group_id = [906932836]

#检查更新
npu_auto_check = true

#服务器状态信息
server_status_enabled = False

#mc服务器motd
MCSTAT_SHOW_ADDR = true

#群消息事件检测
chuo_cd = 10000000
#setu
# 必填项
# api超时，这个时间建议设置一分钟以上，否则发图多的时候容易超时报错
api_timeout = 60
# 管理员的QQ号（别问我为什么要另外写）
tutu_admin_qqnum = 2407187481

#搜图

#pixiv
pixiv_proxy=socks5://127.0.0.1:7890
pixiv_onebot_send_forward_message=auto
pixiv_poke_action=

#网络天才
PROXY="http://127.0.0.1:7890"

#回声洞
WHITE_B_OWNER=["2407187481"]

#定时群名片
set_group_card_hour=1
use_nickname_front=true
self_name="[HF伯特]"

#B站查询

#表情包制作
memes_prompt_params_error=true

#象棋
chess_engine_path=D:\stockfish_15.1_win_x64_avx2\stockfish-windows-2022-x86-64-avx2.exe
cchess_engine_path=D:\stockfish_15.1_win_x64_avx2\fairy-stockfish-largeboard_x86-64.exe

#复读
repeater_min_message_times = 2 # 触发复读的消息次数

#娶群友
waifu_cd_bye = 3600 # 分手冷却时间，默认1小时。
waifu_save = true # 是否将cp记录保存为文件（避免重启bot丢失数据）。
waifu_reset = true # 是否每日重置cp记录。
waifu_he = 25 # 在指定娶群友时，成功的概率25%
waifu_be = 25 # 在指定娶群友时，失败的概率25%
## 成功就是娶到了，失败就是单身。如果这两个参数加起来小于100那么剩下的概率是会随机娶一个。
waifu_ntr = 20 # 别人有cp时被指定娶到的概率
yinpa_he = 50 # 在指定透群友时，成功的概率50%
yinpa_be = 0 # 在指定透群友时，失败的概率0%
## 同上，如果这两个参数加起来不等于100那么剩下的概率是会随机透一个。
yinpa_cp = 65 # 当透群友指定的对象是你娶群友的老婆时用这个概率判定。

#每日推送
linker_group=["906932836"]
send_group_id = ["906932836"]    # 必填 群号
send_switch_morning = True                      # 选填 True/False 默认开启 早上消息推送是否开启
send_switch_night = True                        # 选填 True/False 默认开启 晚上消息推送是否开启
send_mode = 2                 # 选填 默认模式2 模式1发送自定义句子，模式2随机调用一句

#百度翻译

#图片翻译

#steam状态监控

#OSU查询

##方舟查询
# 百度 OCR 配置，公招识别截图用
# 具体见 https://console.bce.baidu.com/ai/?fromai=1#/ai/ocr/app/list

# 代理配置，如部署机器人的服务器在国内大陆地区可能需要修改
GITHUB_RAW="https://raw.githubusercontent.com"   # 默认为 https://raw.githubusercontent.com，如有镜像源可以替换，如 https://ghproxy.com/https://raw.githubusercontent.com
GITHUB_SITE="https://github.com"  # 默认为 https://github.com，如有镜像源可以替换，如 https://kgithub.com
RSS_SITE="https://rsshub.app"  # 默认为 https://rsshub.app，如有镜像源可以替换

# 定时任务配置，默认是关闭的
ANNOUNCE_PUSH_SWITCH=True  # 是否自动推送舟舟最新公告，默认为 False; True 为开启自动检测
ANNOUNCE_PUSH_INTERVAL=60  # 自动推送最新公告的检测间隔，上述开关开启时有效，默认为 1 分钟
SANITY_NOTIFY_SWITCH=False  # 是否自动检测理智提醒，默认为 False; True 为开启自动检测
SANITY_NOTIFY_INTERVAL=10  # 自动检测理智提醒的检测间隔，上述开关开启时有效，默认为 10 分钟

# 启动前素材检查配置，默认是开启的
ARKNIGHTS_UPDATE_CHECK_SWITCH=False  # 是否在启动bot时检查素材版本并下载，默认为True; False 为禁用检查

# 资源路径配置，默认在启动机器人的目录中/运行nb run的目录中/放bot.py的目录中
ARKNIGHTS_DATA_PATH = "data/arktools"                                   # 资源根路径，如果修改了根路径，下方路径都要修改
ARKNIGHTS_FONT_PATH = "data/arktools/fonts"                             # 字体路径
ARKNIGHTS_GAMEDATA_PATH = "data/arktools/arknights/gamedata"            # 游戏数据
ARKNIGHTS_GAMEIMAGE_PATH = "data/arktools/arknights/gameimage"          # 游戏图像
ARKNIGHTS_DB_URL = "data/arktools/databases/arknights_sqlite.sqlite3"   # 数据库

#网易点歌
ncm_admin_level=2 # 设置命令权限(1:仅限superusers和群主,2:在1的基础上+管理员,3:所有用户)
ncm_ctcode="86" # 手机号区域码,默认86
NCM_ILLEGAL_CMD_FINISH = true
NCM_AUTO_RESOLVE = true
NCM_RESOLVE_PLAYABLE_CARD = true

#语音合成
asr_api_provider="baidu" #必填，API提供商，填写“baidu”或“tencent”
nonebot_plugin_gocqhttp=False #选填，是否使用nonebot2插件版本的go-cqhttp，默认为False
```

**Comment by mobyw** [comment]
等会儿我用 PC 看一下，上面的 `caiyunai_apikey` 泄漏了，记得重置一下 API key

**Comment by ABKQPO** [comment]
这个api已经过期了

**Comment by mobyw** [comment]
可以先手动下载仓库里面的 `data` 文件夹，放置到 `nonebot-plugin-localstore` 给插件分配的位置

**Comment by ABKQPO** [comment]
好的

**Comment by ABKQPO** [comment]
可以使用了，谢谢
